
name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Add a step to create the HelloWorldFunction directory and move your code
      - name: Prepare Lambda Code Directory
        run: |
          mkdir -p HelloWorldFunction
          mv src/app.py HelloWorldFunction/
          # If your requirements.txt is also in the src directory:
          mv src/requirements.txt HelloWorldFunction/
          # Add more 'mv' commands for any other necessary files or directories

      - name: Build Lambda Function
        run: |
          sam build --use-container

      # Optional: Preview changes without applying them
      # Remove this block if you’re confident and want auto-deploy
      - name: Preview Changes (Dry Run)
        run: |
          sam deploy \
            --stack-name resume-app \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-execute-changeset \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      # Uncomment the following to actually deploy AFTER preview
      - name: Deploy to AWS
        run: |
          sam deploy \
            --stack-name resume-app \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset